# Generated by Django 4.2.7 on 2023-12-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joylist', '0002_alter_joy_options_remove_joy_compelete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joy',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Detail'),
        ),
        migrations.AlterField(
            model_name='joy',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
